
x-common-log-config: &default_config
  networks:
    - weblogs_lake_network
  env_file:
    - ./conf/.lakehouse.conf
    - ./conf/.secrets.conf

x-common-healthcheck-default: &default_healthcheck
  timeout: 45s
  interval: 10s
  retries: 10
  start_period: 10s

services:

  notebook:
    build: ../docker/customized/notebook
    container_name: notebook
    <<: *default_config
    ports:
      - 8888:8888
    volumes:
      - ../mnt/notebooks:/app/
    environment:
      S3_ENDPOINT: http://minio:9000


  python_job:
    build: ../docker/app_layer/python_jobs
    container_name: python_job
    <<: *default_config
    #entrypoint: "python /app/bronze_to_silver/main.py"
    volumes:
      - ../docker/app_layer/python_jobs/src:/app
    environment:
      BUCKET: warehouse


  spark_job:
    build: ../docker/app_layer/spark_jobs
    container_name: spark_job
    <<: *default_config
    #entrypoint: "sh /app/bronze_to_silver/spark-submit.sh"
    volumes:
      - ../docker/app_layer/spark_jobs/src:/app
    environment:
      EXECUTION_DATE: "2024-10-21 01:00:00+00:00"
      BRONZE_PATH: s3a://breweries/bronze
      SILVER_TABLENAME: nessie.silver.breweries


networks:
  weblogs_lake_network:
    name: weblogs_lake_network