
x-common-log-config: &default_config
  networks:
    - weblogs_lake_network
  env_file:
    - ./conf/.lakehouse.conf
    - ./conf/.secrets.conf
  healthcheck:
    test: [ "CMD", "ls" ]
    timeout: 45s
    interval: 10s
    retries: 10
    start_period: 10s


x-spark-worker-default: &spark_worker_default
  build: ../docker/customized/spark
  <<: *default_config
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark


services:
  spark-master:
    build: ../docker/customized/spark
    container_name: spark-master
    <<: *default_config
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_METRICS_MASTER_ENABLED=true
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '18080:8080'

  spark-worker-1:
    container_name: spark-worker-1
    <<: *spark_worker_default

  spark-worker-2:
    container_name: spark-worker-2
    <<: *spark_worker_default


networks:
  weblogs_lake_network:
    name: weblogs_lake_network
